# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160328_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='time_activation',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='time_delivery',
            field=models.DateField(blank=True),
        ),
    ]
