# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160329_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsule',
            name='activation',
        ),
        migrations.RemoveField(
            model_name='capsule',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='capsule',
            name='time_activation',
        ),
        migrations.AddField(
            model_name='capsule',
            name='activation_type',
            field=models.CharField(choices=[('D', 'Death Activation')], default='D', max_length=10),
        ),
        migrations.AddField(
            model_name='capsule',
            name='author_twitter',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='capsule',
            name='delivery_condition',
            field=models.CharField(choices=[('SD', 'Specific Date In Future'), ('W', 'Wedding'), ('CB', 'Child Birth'), ('M', 'Marriage')], default='SD', max_length=10),
        ),
        migrations.AddField(
            model_name='capsule',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capsule',
            name='is_deliverable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capsule',
            name='target_twitter',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='message',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capsules', to=settings.AUTH_USER_MODEL),
        ),
    ]
