# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 20:40
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160403_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(core.models.make_rng_filename, *('files',), **{})),
        ),
    ]
