# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 01:18
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160404_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='target_email',
            field=models.EmailField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(core.models.make_rng_filename, *('files',), **{})),
        ),
    ]
